# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp
name: Deploy Functions to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'ServerlessDeployment'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Functions' # default path is root directory
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
     - name: 'Checkout Session'
       uses: actions/checkout@v2
     
     - name: Setup Node ${{ env.NODE_VERSION }} Environment
       uses: actions/setup-node@v3
       with:
        node-version: ${{ env.NODE_VERSION }}

     - name: 'Dependency injection and resolve with npm'
       shell: bash
       run: |
        npm install
        npm run build --if-present

     - name: 'Run Azure Function'
       uses: azure/functions-action@v1
       id: fa
       with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH }}


